name:  Node.js Deployment
# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs :
  build :
    runs-on: ubuntu-latest
    steps :
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            cd ./proxy
            git pull
            git status
            npm install
            pm2 restart proxy -i max
